import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ContextAPI from "@/components/context";
import Layout from "./()/layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextAPI>{children}</ContextAPI>
      </body>
    </html>
  );
}
